import { StyleSheet } from 'react-native';

export const FoodListStyles = (isDarkMode) => StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: isDarkMode ? '#121212' : "#f5f7fa",
      padding: 20,
    },
    title: {
      // textAlign: 'center',
      fontSize: 28,
      fontWeight: "800",
      color: isDarkMode ? '#E0E0E0' : "#32745f",
      marginBottom: 16,
      marginTop: 8,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 10,
    },
    dropdownWrapper: {
      width: '25%',
      marginBottom: 10,
      zIndex: 1000,
    },
    dropdownContainer: {
      width: '100%',
    },
    foodItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      padding: 16,
      marginVertical: 8,
      backgroundColor: isDarkMode ? '#242424' : "#fff",
      borderRadius: 20,
      borderWidth: 1,
      borderColor: isDarkMode ? '#333' : "rgba(50, 116, 95, 0.1)",
      shadowColor: isDarkMode ? "#000" : "#32745f",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0.3 : 0.1,
      shadowRadius: 12,
      elevation: 5,
    },
    foodDetails: {
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "flex-start",
      width: "85%",
    },
    foodName: {
      maxWidth: "100%",
      fontSize: 16,
      fontWeight: "800",
      color: isDarkMode ? '#E0E0E0' : "#32745f",
      marginBottom: 4,
    },
    addButton: {
      padding: 10,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: isDarkMode ? '#32745f' : "rgba(50, 116, 95, 0.1)",
      borderRadius: 12,
      marginTop: 0,
      bottom: 0,
    },
    addButtonIcon: {
      color: isDarkMode ? '#E0E0E0' : '#32745f',
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
      width: "90%",
      maxHeight: "90%",
      backgroundColor: isDarkMode ? '#242424' : "#fff",
      borderRadius: 20,
      padding: 16,
    },
    modalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
      marginBottom: 8,
    },
    closeButton: {
      padding: 8,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: isDarkMode ? '#E0E0E0' : "#000",
      flex: 1,
      textAlign: "center",
      marginHorizontal: 10,
    },
    progressWheelRow: {
      flexDirection: "row", // Horizontal layout for progress wheels
      justifyContent: "space-around",
      marginTop: 10,
    },
    progressWheels: {
      flexDirection: "row",
      justifyContent: "space-around",
      flexWrap: "wrap",
      width: "100%",
      marginBottom: 20,
    },
    progressWheelContainer: {
      alignItems: "center",
      marginHorizontal: 10, // Space between each wheel
    },
    wheelLabel: {
      fontSize: 12,
      marginBottom: 4,
      color: isDarkMode ? '#888' : "#666",
      textAlign: "center",
    },
    wheelValue: {
      marginTop: 5,
      fontSize: 12,
      fontWeight: "bold",
      textAlign: "center",
    },
    wheelCenterText: {
      fontSize: 10,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    progressLabel: {
      fontSize: 12,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    subtitle: {
      fontSize: 10,
      fontWeight: 'normal',
      textAlign: 'center',
    },
    wheelWrapper: {
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
    },
    centerValue: {
      position: 'absolute',
      fontSize: 12,
      fontWeight: 'bold',
      color: isDarkMode ? '#E0E0E0' : '#333',
      textAlign: 'center',
    },
    allergenWarning: {
      color: '#FF6B6B',
      fontSize: 12,
      fontWeight: 'bold',
      marginTop: 4,
    },
    dietaryMatch: {
      color: '#32745f',
      fontSize: 12,
      fontWeight: 'bold',
      marginTop: 4,
    },
    emptyMenu: {
      alignItems: 'center',
      paddingVertical: 40,
      paddingHorizontal: 24,
    },
    emptyMenuTitle: {
      fontSize: 17,
      fontWeight: '700',
      textAlign: 'center',
      marginTop: 12,
      color: isDarkMode ? '#E0E0E0' : '#32745f',
    },
    emptyMenuText: {
      fontSize: 14,
      textAlign: 'center',
      marginTop: 8,
      lineHeight: 20,
      color: isDarkMode ? '#AAA' : '#666',
    },
    emptyMenuButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 18,
      backgroundColor: '#32745f',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 12,
    },
    emptyMenuButtonText: {
      color: '#fff',
      fontSize: 15,
      fontWeight: '700',
    },
    estimateLabel: {
      backgroundColor: isDarkMode ? '#2A2A2A' : '#F1F3F5',
      borderColor: isDarkMode ? '#555' : '#B0B8BF',
      borderWidth: 1,
    },
    estimateLabelText: {
      color: isDarkMode ? '#BBB' : '#5F6B75',
    },
    labelContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 4,
      marginTop: 4,
    },
    label: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 4,
      marginRight: 4,
      marginBottom: 4,
    },
    allergenLabel: {
      backgroundColor: '#FFE8E8',
      borderColor: '#FF6B6B',
      borderWidth: 1,
    },
    preferenceLabel: {
      backgroundColor: '#E8F5E9',
      borderColor: '#32745f',
      borderWidth: 1,
    },
    labelText: {
      fontSize: 10,
      fontWeight: 'bold',
    },
    allergenLabelText: {
      color: '#FF6B6B',
    },
    preferenceLabelText: {
      color: '#32745f',
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: isDarkMode ? '#E0E0E0' : '#32745f',
      marginBottom: 6,
    },
    section: {
      marginTop: 6,
      width: '100%',
    },
    nutritionSection: {
      marginTop: 12,
      width: '100%',
      paddingBottom: 12,
    },
    nutritionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 6,
    },
    nutritionItem: {
      width: '31%',
      marginBottom: 6,
      padding: 8,
      backgroundColor: isDarkMode ? '#333' : '#f5f5f5',
      borderRadius: 8,
    },
    nutritionLabel: {
      fontSize: 12,
      color: isDarkMode ? '#888' : '#666',
      marginBottom: 4,
    },
    nutritionValue: {
      fontSize: 14,
      fontWeight: '600',
      color: isDarkMode ? '#E0E0E0' : '#32745f',
    },
    nutritionSubLabel: {
      fontSize: 11,
      color: isDarkMode ? '#AAAAAA' : '#666666',
      marginTop: 2,
    },
    servingSizeText: {
      marginTop: 4,
      fontSize: 13,
      color: isDarkMode ? '#CCCCCC' : '#555555',
      textAlign: 'center',
    },
    tagContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    tag: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 16,
      marginRight: 6,
      marginBottom: 6,
    },
    allergenTag: {
      backgroundColor: '#FFE8E8',
      borderColor: '#FF6B6B',
      borderWidth: 1,
    },
    traitTag: {
      backgroundColor: '#E8F5E9',
      borderColor: '#32745f',
      borderWidth: 1,
    },
    allergenText: {
      color: '#FF6B6B',
      fontSize: 14,
      fontWeight: '500',
    },
    traitText: {
      color: '#32745f',
      fontSize: 14,
      fontWeight: '500',
    },
    modalScroll: {
      flexGrow: 1,
      width: '100%',
    },
    macroRow: {
      paddingVertical: 6,
      borderBottomWidth: 1,
      borderBottomColor: isDarkMode ? '#333' : 'rgba(0,0,0,0.1)',
      marginBottom: 8,
    },
    macroText: {
      fontSize: 14,
      color: isDarkMode ? '#E0E0E0' : '#32745f',
      textAlign: 'center',
    },
    modalScrollContent: {
      paddingBottom: 16,
    },
    searchAndFilterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 4,
      marginBottom: 8,
    },
    searchContainer: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDarkMode ? '#242424' : '#FFFFFF',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDarkMode ? '#333' : 'rgba(50, 116, 95, 0.15)',
      marginRight: 8,
      paddingHorizontal: 8,
      paddingVertical: 6,
      shadowColor: isDarkMode ? "#000" : "#32745f",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDarkMode ? 0.2 : 0.1,
      shadowRadius: 8,
      elevation: 3,
      minHeight: 36,
    },
    searchContainerFocused: {
      backgroundColor: isDarkMode ? '#1A1A1A' : '#FFFFFF',
      borderWidth: 2,
      borderColor: '#32745f',
      shadowColor: "#32745f",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: isDarkMode ? 0.4 : 0.25,
      shadowRadius: 16,
      elevation: 8,
    },
    searchIconContainer: {
      marginRight: 8,
      justifyContent: 'center',
      alignItems: 'center',
      width: 20,
      height: 20,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: isDarkMode ? '#E0E0E0' : '#333',
      paddingVertical: 0,
      paddingHorizontal: 0,
      textAlignVertical: 'center',
      includeFontPadding: false,
      fontWeight: '500',
      height: 20,
    },
    clearButton: {
      marginLeft: 8,
      borderRadius: 14,
      backgroundColor: isDarkMode ? 'rgba(50, 116, 95, 0.2)' : 'rgba(50, 116, 95, 0.15)',
      justifyContent: 'center',
      alignItems: 'center',
      width: 28,
      height: 28,
    },
    filterButton: {
      width: 36,
      height: 36,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDarkMode ? '#333333' : 'rgba(50, 116, 95, 0.2)',
      backgroundColor: isDarkMode ? '#1F1F1F' : '#F1F5F3',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: isDarkMode ? 'transparent' : '#32745f',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDarkMode ? 0.18 : 0.12,
      shadowRadius: 6,
      elevation: 3,
    },
    filterButtonActive: {
      borderColor: '#32745f',
      backgroundColor: isDarkMode ? 'rgba(50, 116, 95, 0.25)' : 'rgba(50, 116, 95, 0.18)',
    },
    filterModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
      justifyContent: 'center',
      padding: 20,
    },
    filterModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    filterModalContent: {
      backgroundColor: isDarkMode ? '#1D1D1D' : '#FFFFFF',
      borderRadius: 18,
      padding: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 12,
      maxHeight: '85%',
    },
    filterModalScroll: {
      marginTop: 4,
      flexGrow: 1,
      flexShrink: 1,
      minHeight: 0,
    },
    filterModalScrollContent: {
      paddingBottom: 12,
    },
    filterModalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    filterModalTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: isDarkMode ? '#E0E0E0' : '#1A1A1A',
    },
    filterCloseButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: isDarkMode ? '#2A2A2A' : '#F2F2F2',
    },
    filterSection: {
      marginTop: 16,
    },
    filterSectionTitle: {
      fontSize: 13,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      color: isDarkMode ? '#9E9E9E' : '#6E7A75',
      fontWeight: '700',
    },
    filterOptionRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDarkMode ? '#2F2F2F' : 'rgba(50, 116, 95, 0.12)',
      marginTop: 10,
      backgroundColor: isDarkMode ? '#242424' : '#F9FBFA',
    },
    filterOptionRowActive: {
      borderColor: '#32745f',
      backgroundColor: isDarkMode ? 'rgba(50, 116, 95, 0.2)' : 'rgba(50, 116, 95, 0.15)',
    },
    filterOptionIcon: {
      marginRight: 12,
      marginTop: 2,
    },
    filterOptionTextWrapper: {
      flex: 1,
    },
    filterOptionTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: isDarkMode ? '#E0E0E0' : '#1F2A27',
    },
    filterOptionSubtitle: {
      fontSize: 12,
      color: isDarkMode ? '#A8A8A8' : '#4F5C58',
      marginTop: 2,
      lineHeight: 16,
    },
    filterSwitchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 16,
    },
    filterSwitchTextWrapper: {
      flex: 1,
      paddingRight: 12,
    },
    filterSwitchTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: isDarkMode ? '#E0E0E0' : '#1F2A27',
    },
    filterSwitchSubtitle: {
      fontSize: 12,
      color: isDarkMode ? '#A8A8A8' : '#4F5C58',
      marginTop: 2,
      lineHeight: 16,
    },
    filterFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 24,
    },
    filterFooterButtonSecondary: {
      flex: 1,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: isDarkMode ? '#3A3A3A' : '#C8D6D1',
      paddingVertical: 12,
      paddingHorizontal: 16,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
    },
    filterFooterButtonSecondaryText: {
      fontSize: 14,
      fontWeight: '600',
      color: isDarkMode ? '#E0E0E0' : '#1F2A27',
    },
    filterFooterButtonPrimary: {
      flex: 1,
      borderRadius: 10,
      backgroundColor: '#32745f',
      paddingVertical: 12,
      paddingHorizontal: 16,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 8,
    },
    filterFooterButtonPrimaryText: {
      fontSize: 14,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    popupContainer: {
      position: 'absolute',
      bottom: 10,
      right: 20,
      zIndex: 9999,
    },
    popup: {
      width: 280,
      borderRadius: 12,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 8,
    },
    popupSuccess: {
      backgroundColor: isDarkMode ? '#242424' : '#FFFFFF',
      borderLeftWidth: 4,
      borderLeftColor: '#4CAF50',
      borderWidth: 1,
      borderColor: isDarkMode ? '#333' : 'rgba(76, 175, 80, 0.2)',
    },
    popupError: {
      backgroundColor: isDarkMode ? '#242424' : '#FFFFFF',
      borderLeftWidth: 4,
      borderLeftColor: '#F44336',
      borderWidth: 1,
      borderColor: isDarkMode ? '#333' : 'rgba(244, 67, 54, 0.2)',
    },
    popupInfo: {
      backgroundColor: isDarkMode ? '#242424' : '#FFFFFF',
      borderLeftWidth: 4,
      borderLeftColor: '#2196F3',
      borderWidth: 1,
      borderColor: isDarkMode ? '#333' : 'rgba(33, 150, 243, 0.2)',
    },
    popupContent: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    popupIcon: {
      marginRight: 8,
    },
    popupText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '600',
      color: isDarkMode ? '#E0E0E0' : '#333',
      lineHeight: 18,
    },
    popupProgressBar: {
      height: 3,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    popupProgressSuccess: {
      backgroundColor: '#4CAF50',
    },
    popupProgressError: {
      backgroundColor: '#F44336',
    },
    popupProgressInfo: {
      backgroundColor: '#2196F3',
    },
});

export const HeaderSelectorStyles = (isDarkMode) => StyleSheet.create({
    dropdown: {
      backgroundColor: isDarkMode ? '#242424' : "#fff",
      borderColor: isDarkMode ? '#333' : "rgba(50, 116, 95, 0.1)",
      borderRadius: 12,
      minHeight: 40,
      borderWidth: 1,
    },
    dropDownBox: {
      backgroundColor: isDarkMode ? '#242424' : "#fff",
      borderColor: isDarkMode ? '#333' : "rgba(50, 116, 95, 0.1)",
      borderRadius: 12,
    },
    headerText: {
      fontSize: 14,
      fontWeight: "600",
      color: isDarkMode ? '#888' : "#666",
      marginBottom: 5,
    },
    dropdownWrapper: {
      width: '48%',
      marginBottom: 10,
      zIndex: 1000,
      gap: 8,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 10,
    },
});
