import { StyleSheet } from 'react-native';

export const signInStyles = (isDarkMode) => StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: isDarkMode ? '#121212' : '#fff',
      paddingTop: '15%',
      paddingHorizontal: 20,
    },
    headerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 30,
      position: 'relative',
    },
    backButton: {
      position: 'absolute',
      left: 0,
      zIndex: 1,
      padding: 5,
    },
    title: {
      fontSize: 28,
      fontWeight: "800",
      color: "#32745f",
      flex: 1,
      textAlign: 'center',
    },
    input: {
      height: 55,
      width: "100%",
      borderColor: isDarkMode ? '#333' : "rgba(50, 116, 95, 0.2)",
      borderWidth: 1.5,
      borderRadius: 12,
      paddingHorizontal: 15,
      marginBottom: 20,
      fontSize: 16,
      backgroundColor: isDarkMode ? '#242424' : "#fff",
      color: isDarkMode ? '#E0E0E0' : "#32745f",
    },
    passwordContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderColor: isDarkMode ? '#333' : "rgba(50, 116, 95, 0.2)",
      borderWidth: 1.5,
      borderRadius: 12,
      width: "100%",
      paddingHorizontal: 15,
      marginBottom: 20,
      backgroundColor: isDarkMode ? '#242424' : "#fff",
    },
    passwordInput: {
      flex: 1,
      fontSize: 16,
      height: 55,
      color: isDarkMode ? '#E0E0E0' : "#32745f",
    },
    button: {
      backgroundColor: "#32745f",
      paddingVertical: 16,
      width: "100%",
      borderRadius: 12,
      alignItems: "center",
      marginBottom: 15,
      shadowColor: isDarkMode ? '#000' : "#32745f",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 5,
    },
    buttonText: {
      color: "#fff",
      fontSize: 18,
      fontWeight: "700",
      letterSpacing: 0.5,
    },
    linkText: {
      marginTop: 15,
      color: isDarkMode ? '#E0E0E0' : "#2E7D32",
      fontSize: 16,
      textAlign: "center",
      fontWeight: "600",
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
      backgroundColor: isDarkMode ? '#242424' : "#fff",
      padding: 25,
      borderRadius: 20,
      width: "90%",
      alignItems: "center",
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: isDarkMode ? '#E0E0E0' : "#32745f",
      marginBottom: 20,
    },
    cancelButton: {
      backgroundColor: 'transparent',
      paddingVertical: 16,
      width: "100%",
      borderRadius: 12,
      alignItems: "center",
      marginBottom: 15,
      borderWidth: 1.5,
      borderColor: isDarkMode ? '#E0E0E0' : "#32745f",
    },
    cancelButtonText: {
      color: isDarkMode ? '#E0E0E0' : "#32745f",
      fontSize: 18,
      fontWeight: "700",
      letterSpacing: 0.5,
    },
});