module.exports = {
  slug: 'umich',
  name: 'University of Michigan',
  listingUrl: 'https://dining.umich.edu/menus-locations/dining-halls/',
  adapter: 'umich',
  fetchMode: 'browser',
  ignoreHallSlugs: ['select-access'],
  selectors: {
    listingHallLinks: '.level_2',
    hallName: 'a.level_2.active, .titleText',
    mealHeading: 'h3 > a',
    mealHeadingItemsContainer: 'next',
    mealHeadingItemsSelector: 'li',
    courseSections: 'ul.courses_wrapper > li:has(ul.items)',
    courseTitle: 'h4',
    courseItems: 'ul.items > li',
    itemName: '.item-name',
    itemAllergens: '.allergens ul li',
    itemTraits: '.traits li',
    nutritionRows: '.nutrition-facts tbody tr',
    nutritionRowLabel: 'td:first-child',
    nutritionRowValue: 'td:last-child',
  },
};
