module.exports = {
  slug: 'ut-austin',
  name: 'UT Austin',
  listingUrl: 'https://housing.utexas.edu/dining/menu',
  adapter: 'ut-austin',
  fetchMode: 'http',
  selectors: {
    listingHallLinks: '.location-list .hall-link',
    hallName: '.hall-name',
    mealBlocks: '.meal-block',
    mealName: '.meal-title',
    stationBlocks: '.station',
    stationName: '.station-title',
    items: '.menu-item',
    itemName: '.name',
    itemAllergens: '.allergens li',
    itemTraits: '.traits li',
    nutritionRows: '.nutrition > div',
    nutritionRowLabel: 'dt',
    nutritionRowValue: 'dd',
  },
};
