// Concatenates every database file, in order, into src/db/setup.sql so a
// fresh Supabase project needs one paste into the SQL editor:
//   npm run db:setup-sql
// Every file is idempotent, so re-running setup.sql on an existing project is safe.
const fs = require('fs');
const path = require('path');

const DB_DIR = path.join(__dirname, '..', 'db');
const PARTS = [
  'schema.sql',
  'migrations/002_multi_school_social.sql',
  'migrations/003_profiles.sql',
  'seed/schools.sql',
];

function buildSetupSql() {
  const sections = PARTS.map(
    (part) => `-- ======================================================================\n-- ${part}\n-- ======================================================================\n${fs.readFileSync(path.join(DB_DIR, part), 'utf8').trimEnd()}\n`
  );
  return `-- Generated by \`npm run db:setup-sql\`. Do not edit by hand; edit the files listed below.\n-- Paste into the Supabase SQL editor and run. Safe to re-run.\n\n${sections.join('\n')}`;
}

if (require.main === module) {
  process.stdout.write(buildSetupSql());
}

module.exports = {
  buildSetupSql,
};
