// Prints src/db/seed/schools.sql from src/config/catalog.js:
//   npm run db:seed-sql
// Re-running the seed updates school metadata but never demotes a live school.
const { catalog, gyms } = require('../config/catalog');

function literal(value) {
  if (value === null || value === undefined) return 'null';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function arrayLiteral(values) {
  return `array[${values.map(literal).join(', ')}]::text[]`;
}

function buildSeedSql() {
  const rows = catalog.map(
    (s) =>
      `  (${[
        literal(s.slug),
        literal(s.name),
        literal(s.shortName),
        arrayLiteral(s.emailDomains),
        literal(s.city),
        literal(s.state),
        literal(s.timezone),
        literal(s.platform),
        literal(s.status),
      ].join(', ')})`
  );

  const gymRows = Object.entries(gyms).flatMap(([schoolSlug, list]) =>
    list.map((gym) => `  (${literal(schoolSlug)}, ${literal(gym.slug)}, ${literal(gym.name)})`)
  );

  return `-- Generated by \`npm run db:seed-sql\` from src/config/catalog.js. Do not edit by hand.
insert into public.schools (slug, name, short_name, email_domains, city, state, timezone, menu_platform, status)
values
${rows.join(',\n')}
on conflict (slug) do update set
  name = excluded.name,
  short_name = excluded.short_name,
  email_domains = excluded.email_domains,
  city = excluded.city,
  state = excluded.state,
  timezone = excluded.timezone,
  menu_platform = excluded.menu_platform,
  status = case when public.schools.status = 'live' then 'live' else excluded.status end,
  updated_at = now();

-- Gyms (names only; coordinates are set per school and never overwritten here).
insert into public.gym_facilities (school_id, slug, name)
select s.id, v.slug, v.name
from (values
${gymRows.join(',\n')}
) as v(school_slug, slug, name)
join public.schools s on s.slug = v.school_slug
on conflict (school_id, slug) do update set name = excluded.name;
`;
}

if (require.main === module) {
  process.stdout.write(buildSeedSql());
}

module.exports = {
  buildSeedSql,
};
